### PR TITLE
Add config parser from json

### PR DESCRIPTION
**Pull request by duckoder**
- removed `config.json` from version control
- added the config example file
- added the config parser

### CODE REVIEW

**Comment by samschurter** [comment]
thanks, I'll take a look at this soon

**Review by aaronarduino — APPROVED** [review]
Looks good to me.

**Comment by samschurter** [comment]
@aaronarduino if you check your inbox you should have an invite to be a collaborator with write access, then you can approve PR's.
I've read through the code and it looks good to me, too

**Comment by duckoder** [comment]
@SkippOtter @aaronarduino I've added configuration usage for database connection

**Pull request merged**
